id: 8fbb414b5fc2486a91539dd11c50021c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_134-The_Absorption_That_Encapsulates_All_Merit-v2
  language: bo
  author: ''
  volume: {}
